server:
  port: 8082
spring:
  application:
    name: md-order
  datasource:
    url: jdbc:mysql://192.168.1.7:3307/md_order
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka