logging:
  config: classpath:log/logback.cfg.xml
spring:
  application:
    name: fd-account
  datasource:
    url: jdbc:mysql://192.168.1.6:3309/ps_account
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: fd-account
  protocol:
    name: dubbo
    port: 20882
  server: true
  registry:
    address: nacos://192.168.1.6:8848