logging:
  config: classpath:log/logback-spring.xml
spring:
  storeage-datasource:
    url: jdbc:mysql://192.168.1.6:3308/ps_storage
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
  order-datasource:
    url: jdbc:mysql://192.168.1.6:3307/ps_order
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
