server:
  port: 8082
  servlet:
    context-path: /ms-user
spring:
  application:
    name: ms-user
  datasource:
    username: root
    password: lotus
    url: jdbc:mysql://192.168.1.6:3308/ms_user?sessionVariables=foreign_key_checks=0&serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka
