server:
  port: 8081
spring:
  application:
    name: proxy
eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    serviceUrl:
      defaultZone: http://localhost:8080@localhost:8761/eureka
