logging:
  config: classpath:log/logback.cfg.xml
spring:
  application:
    name: fd-storage
  datasource:
    url: jdbc:mysql://192.168.1.6:3308/ps_storage
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: fd-storage
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.1.6:2181