server:
  port: 8761

spring:
  application:
    name: microservice-registry

eureka:
  client:
    register-with-eureka: false # 集群时注册自己
    fetch-registry: false # 查找现有的注册中心
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka

security:
  basic:
    enable: true
  user:
    name: ps
    password: lotus