logging:
  config: classpath:log/logback.cfg.xml
spring:
  order-datasource:
    url: jdbc:mysql://192.168.105.129:3307/ps_order
    username: root
    password: lotus
    driver-class-name: com.mysql.cj.jdbc.Driver
  storage-datasource:
    url: jdbc:mysql://192.168.105.129:3308/ps_storage
    username: root
    password: lotus
    driver-class-name: com.mysql.cj.jdbc.Driver

