server:
  port: 8081
spring:
  application:
    name: md-ticket
  datasource:
    url: jdbc:mysql://192.168.1.7:3309/md-ticket
    username: root
    password: lotus
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    servcieUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka