server:
  port: 8082
spring:
  application:
    name: md-storage
  datasource:
    url: jdbc:mysql://192.168.1.6:3308/ps_storage
    username: root
    password: lotus
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    url: tcp://192.168.1.6:61616
eureka:
  client:
    serviceUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka