logging:
  config: classpath:log/logback.cfg.xml
spring:
  application:
    name: fd-order
  datasource:
    url: jdbc:mysql://192.168.1.6:3307/ps_order
    username: root
    password: lotus
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: fd-order
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.1.6:2181