server:
  port: 8080
spring:
  application:
    name: ms-proxy
eureka:
  client:
    register-with_eureka: true
    fetch-register: true
    serviceUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka
zuul:
  routes:
    userApi:
      path: /home/**
      serviceId: user
      stripPrefix: false