server:
  port: 8080
spring:
  application:
    name: ms-proxy
eureka:
  client:
#    register-with-eureka: true
#    fetch-register: true
    serviceUrl:
      defaultZone: http://ps:lotus@localhost:8761/eureka
zuul:
  routes:
    userApi:
      path: /api/v1/**
      serviceId: ms-order
      stripPrefix: false